// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozvaomfsovstfeeezxpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dmFvbWZzb3ZzdGZlZWV6eHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NjY1MDAsImV4cCI6MjA4NjU0MjUwMH0.T9PW2J71CiQ93syh7EdmOa7YAA5-7YmrqV9RED0GqjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});